### PR TITLE
ci: disable `standard` linter

### PR DESCRIPTION
**Pull request by bajtos**
Avoid https://github.com/standard/standard/issues/1976

### CODE REVIEW

**Comment by bajtos** [comment]
It looks like https://github.com/space-meridian/roadmap/issues/166 becomes a somewhat urgent task.

**Review by juliangruber — CHANGES_REQUESTED** [review]
I believe it's a matter of hours or max a day until this is fixed, so I'd rather wait until then

**Comment by juliangruber** [comment]
> It looks like [space-meridian/roadmap#166](https://github.com/space-meridian/roadmap/issues/166) becomes a somewhat urgent task.

This is a temporary hickup and is being fixed, I don't think this requires us to switch away now

**Comment by voxpelli** [comment]
I released `standard@17.1.1` that pins the regressed dependency, so this is no longer necessary

**Pull request closed without merging**
