### PR TITLE
Feat: Get station_id from Zinnia env and add to measurements submission

### PR DESCRIPTION
**Pull request by PatrickNercessian**
Links:
filecoin-station/roadmap#96

### CODE REVIEW

**Comment by juliangruber** [comment]
Depends on https://github.com/filecoin-station/zinnia/pull/520

**Review by juliangruber — APPROVED** [review]

**Review by bajtos — CHANGES_REQUESTED** [review]
The code change LGTM 👌🏻 

You will need to update the CI workflow to fetch the new Zinnia version. (After we land your Zinnia PR and publish a new version.)

https://github.com/filecoin-station/spark/blob/e78405179c0e49a2ae56b13c0d035372690a106b/.github/workflows/ci.yml#L8

**Review by bajtos — APPROVED** [review]
👍🏻

**Comment by bajtos** [comment]
Landed via #60. I couldn't figure out why GitHub refused to run the CI workflow.

**Pull request closed without merging**
